name: The Sorting Hat
author: Lisa Dean https://github.com/lisadean
description: 'GitHub App to sort things with labels'
branding:
    icon: 'tag'
    color: blue
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
    required: true
outputs:
  labels:
    description: 'New list of PR labels after action run'
  skip-deploy:
    description: 'Skip deployment based on files being pushed? Returns "true"
      or "false" -- must compare as a string value in the "if" expression.'
runs:
    using: 'node12'
    main: 'dist/index.js'
