name: The Sorting Hat
author: Lisa Dean https://github.com/lisadean
description: 'GitHub App to sort things with labels'
branding:
    icon: 'tag'
    color: blue
runs:
    using: 'node12'
    main: 'dist/index.js'
