name: Test workflow
on:
  pull_request:

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Run GH action from dev branch
        uses: lisadean/the-sorting-hat
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
