name: Release to vdev
on:
    push:
      branches:
        - dev
jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - uses: styfle/cancel-workflow-action@0.8.0
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run build
            - run: echo '!dist' >> .gitignore # un-ignore dist folder
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - run: 'git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/vdev'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
