name: Release to development branch
on:
    push:
      branches:
        - 'SODEV*'
jobs:
    release:
        name: release-development-branch
        runs-on: ubuntu-latest
        steps:
            - uses: styfle/cancel-workflow-action@0.8.0
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Dump github context
              env:
                  GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
            - name: Build
              run: |
                npm ci
                npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Commit dist folder and push to development branch
              run: |
                if [[ `git status --porcelain` ]]; then
                  git config user.name "Automation"
                  git config user.email Automation@build.com
                  git add --force ./dist/*
                  git commit -m "ncc build files"
                  git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
                fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
