name: Main - Release to v1

on:
    push:
        branches:
            - main
jobs:
    release:
        name: Release to v1 branch
        runs-on: ubuntu-latest
        steps:
            - name: Cancel all other runs of this workflow
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
                  all_but_latest: true
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
            - name: Install node modules
              run: npm ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Bump version & tag
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Build
              run: npm run build
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Commit dist folder and push to v1 branch
              run: |
                if [[ `git status --porcelain` ]]; then
                  git config user.name "Automation"
                  git config user.email Automation@build.com
                  git add --force ./dist/*
                  git commit -m "ncc build files"
                  git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1
                fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
