name: Main - Release to v1

on:
    push:
        branches:
            - main
jobs:
    release:
        name: Release to v1 branch
        runs-on: ubuntu-latest
        steps:
            - name: Cancel all other runs of this workflow
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
                  all_but_latest: true
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
            - name: Bump version & tag
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Push main branch to v1
              run: |
                git config user.name "Automation"
                git config user.email Automation@build.com
                git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
